/* kernel/include/sys/abi.h — D74 auto-generated by tools/translate_abi.py
 * SSOT: kernel/include/sys/abi.zig
 * D121 白名单 5 struct 之一: sys_result_t / sys_result_payload_t
 *
 * ⚠️ HANDWRITTEN marker: 本轮因 PowerShell 把 stderr "extracted:" 当 RemoteException
 *    的问题 (D-ENV-07), translate_abi.py stderr 会被 PowerShell 拦, 故本轮用手写
 *    占位 + 编译期三端 assert 块 (D121 白名单要求: "要么 SSOT 生成, 要么手写 + 断言").
 *    升级路径: R52 引入 bash-only translate_abi.py runner, 改回自动生成.
 */

#ifndef KERNEL_INCLUDE_SYS_ABI_H
#define KERNEL_INCLUDE_SYS_ABI_H

#include <stdint.h>
#include <stddef.h>

/* === D86 + P2-1 carve-out: error_pack 单层 scalar-only struct (D90 唯一豁免) === */
typedef struct __attribute__((packed)) {
    uint16_t remote_node_id;   /* D4 position transparency (0xFFFF = local) */
    uint16_t subsystem_id;
    int32_t  error_code;       /* P2-2 errno always negative */
} sys_error_pack_t;
_Static_assert(sizeof(sys_error_pack_t) == 8, "D85/P2-1: error_pack must be 8B");
_Static_assert(offsetof(sys_error_pack_t, remote_node_id) == 0, "D85: remote_node_id @0");
_Static_assert(offsetof(sys_error_pack_t, subsystem_id)   == 2, "D85: subsystem_id @2");
_Static_assert(offsetof(sys_error_pack_t, error_code)     == 4, "D85: error_code @4");

/* === D89: sys_result_payload_t 8B union === */
typedef union {
    uint64_t        value;
    sys_error_pack_t error_pack;
} sys_result_payload_t;
_Static_assert(sizeof(sys_result_payload_t) == 8, "D86/D89: payload must be 8B");

/* === D86: sys_result_t 严格 16B = 2×XLEN, a0/a1 寄存器对返回 === */
typedef struct {
    uint32_t             header;     /* P1-2: bit 31 = is_error, bits 0-30 = flags */
    uint32_t             reserved;   /* R48 旧 status: u32 废除, 改 reserved */
    sys_result_payload_t payload;
} __attribute__((aligned(8))) sys_result_t;
_Static_assert(sizeof(sys_result_t) == 16, "D86: sys_result_t must be 16B (= 2×XLEN)");
_Static_assert(_Alignof(sys_result_t) == 8, "D86: sys_result_t must be 8B align");

/* === D57/D85: rpc_unit_t 1536B frozen === */
typedef struct {
    uint64_t header;
    uint8_t  payload[1528];
} rpc_unit_t;
_Static_assert(sizeof(rpc_unit_t) == 1536, "D57: rpc_unit_t must be 1536B");

/* === D57/D60: network_frame_t 1536B frozen (14B MAC DMA 在 1536B 外) === */
typedef struct {
    uint64_t header;
    uint8_t  payload[1528];
} network_frame_t;
_Static_assert(sizeof(network_frame_t) == 1536, "D57: network_frame_t must be 1536B");

/* === D57: block_t 1536B frozen === */
typedef struct {
    uint8_t bytes[1536];
} block_t;
_Static_assert(sizeof(block_t) == 1536, "D57: block_t must be 1536B");

#endif /* KERNEL_INCLUDE_SYS_ABI_H */
