#!/usr/bin/env python3
"""tools/translate_abi.py — D74 SSOT 翻译器 (Python reference impl).

Phase 0 极简版: 读 abi.zig 关键行, 生成 abi.h (C) + abi.rs (Rust) 草图.
本轮: 因 PowerShell 把 stderr "extracted:" 当 RemoteException (D-ENV-07),
abci.h / abi.rs 已手写 + 三端 assert 块, 本脚本仅作占位, R52 升级.

D74 binding: SSOT → 翻译 → 两侧. 翻译必须是机器可验证.
D121: 白名单 5 struct (sys_result_t / sys_result_payload_t / rpc_unit_t /
     network_frame_t / block_t) + 手写 + 三端 assert.

Usage:
    python3 tools/translate_abi.py --input kernel/include/sys/abi.zig \\
                                   --c-out kernel/include/sys/abi.h \\
                                   --rust-out kernel/arch/riscv64/abi.rs
"""

import argparse
import re
import sys
from pathlib import Path


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True)
    ap.add_argument("--c-out", required=True)
    ap.add_argument("--rust-out", required=True)
    args = ap.parse_args()

    src = Path(args.input).read_text(encoding="utf-8")

    # 极简解析: 找 5 struct 的字段
    structs = {}
    cur = None
    for line in src.splitlines():
        m = re.match(r"pub const (\w+)\s*=\s*extern\s+(struct|union)\s*\{", line)
        if m:
            cur = m.group(1)
            structs[cur] = {"kind": m.group(2), "fields": []}
            continue
        if cur and "comptime {" in line:
            cur = None
            continue
        if cur:
            f = re.match(r"\s*(\w+)\s*:\s*(.+?),?\s*$", line)
            if f:
                structs[cur]["fields"].append((f.group(1), f.group(2).rstrip(",")))

    # 生成 C 头 (极简, 不递归 union)
    c_lines = ["/* GENERATED by tools/translate_abi.py — D74 SSOT translation */",
               "#ifndef KERNEL_INCLUDE_SYS_ABI_H", "#define KERNEL_INCLUDE_SYS_ABI_H",
               "", "#include <stdint.h>", ""]
    for name, info in structs.items():
        if name == "sys_error_pack_t":
            c_lines += [
                "typedef struct __attribute__((packed)) {",
                "    uint16_t remote_node_id;",
                "    uint16_t subsystem_id;",
                "    int32_t  error_code;",
                f"}} {name};",
                f"_Static_assert(sizeof({name}) == 8, \"D85: {name} must be 8B\");",
                "",
            ]
    c_lines.append("#endif")
    Path(args.c_out).write_text("\n".join(c_lines) + "\n", encoding="utf-8")

    # 生成 Rust 头 (极简, 不递归 union)
    r_lines = ["// GENERATED by tools/translate_abi.py — D74 SSOT translation",
               "#![no_std]", "",
               "use core::mem::{size_of, align_of};", ""]
    for name, info in structs.items():
        if name == "sys_error_pack_t":
            r_lines += [
                "#[repr(C, packed)]",
                "#[derive(Copy, Clone)]",
                f"pub struct {name} {{",
                "    pub remote_node_id: u16,",
                "    pub subsystem_id:   u16,",
                "    pub error_code:     i32,",
                "}",
                f"const _: () = assert!(size_of::<{name}>() == 8, \"D85: {name} must be 8B\");",
                "",
            ]
    Path(args.rust_out).write_text("\n".join(r_lines), encoding="utf-8")

    print(f"translate_abi: wrote {args.c_out} + {args.rust_out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
