// kernel/arch/riscv64/abi.rs — D74 auto-generated by tools/translate_abi.py
// SSOT: kernel/include/sys/abi.zig
// D121 白名单 5 struct 之一: sys_result_t / sys_result_payload_t
//
// ⚠️ HANDWRITTEN marker: 同 abi.h, 本轮用"手写 + 三端 assert"模式 (D121 允).
//   R52 升级回 auto-gen.

#![no_std]

use core::mem::{size_of, align_of};

/* === D86 + P2-1 carve-out: error_pack (D90 唯一豁免, scalar-only struct) === */
#[repr(C, packed)]
#[derive(Copy, Clone)]
pub struct sys_error_pack_t {
    pub remote_node_id: u16,    // D4 position transparency (0xFFFF = local)
    pub subsystem_id:   u16,
    pub error_code:     i32,    // P2-2 errno always negative
}
const _: () = {
    assert!(size_of::<sys_error_pack_t>() == 8, "D85/P2-1: error_pack must be 8B");
};

/* === D89: sys_result_payload_t 8B union === */
#[repr(C, align(8))]
pub union sys_result_payload_t {
    pub value:      u64,
    pub error_pack: core::mem::ManuallyDrop<sys_error_pack_t>,
}
const _: () = {
    assert!(size_of::<sys_result_payload_t>() == 8, "D86/D89: payload must be 8B");
};

/* === D86: sys_result_t 严格 16B = 2×XLEN, a0/a1 寄存器对返回 === */
#[repr(C, align(8))]
#[derive(Copy, Clone)]
pub struct sys_result_t {
    pub header:   u32,             // P1-2: bit 31 = is_error
    pub reserved: u32,             // R48 旧 status: u32 废除
    pub payload:  sys_result_payload_t,
}
const _: () = {
    assert!(size_of::<sys_result_t>() == 16, "D86: sys_result_t must be 16B");
    assert!(align_of::<sys_result_t>() == 8,  "D86: sys_result_t must be 8B align");
};

/* === D57/D85: rpc_unit_t 1536B frozen === */
#[repr(C)]
#[derive(Copy, Clone)]
pub struct rpc_unit_t {
    pub header:  u64,
    pub payload: [u8; 1528],
}
const _: () = {
    assert!(size_of::<rpc_unit_t>() == 1536, "D57: rpc_unit_t must be 1536B");
};

/* === D57/D60: network_frame_t 1536B frozen (14B MAC DMA 在 1536B 外) === */
#[repr(C)]
#[derive(Copy, Clone)]
pub struct network_frame_t {
    pub header:  u64,
    pub payload: [u8; 1528],
}
const _: () = {
    assert!(size_of::<network_frame_t>() == 1536, "D57: network_frame_t must be 1536B");
};

/* === D57: block_t 1536B frozen === */
#[repr(C)]
#[derive(Copy, Clone)]
pub struct block_t {
    pub bytes: [u8; 1536],
}
const _: () = {
    assert!(size_of::<block_t>() == 1536, "D57: block_t must be 1536B");
};
